# Generated by Django 5.2 on 2025-04-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_class', models.IntegerField()),
                ('student_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
